apiVersion: servicedefinition.sz-ybbs.ac.at/v1alpha1
kind: Servicedefinition
metadata:
  name: "andreas"
  namespace: "manual-services"
spec:
  cms:
    name: "Typo3"
    version: "1"
  owner: andreas
  purpose: operatorTest
