apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicedefinition
spec:
  replicas: 1
  selector:
    matchLabels:
      name: servicedefinition
  template:
    metadata:
      labels:
        name: servicedefinition
    spec:
      serviceAccountName: servicedefinition
      containers:
        - name: servicedefinition
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - servicedefinition
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "servicedefinition"
