kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: servicedefinition
subjects:
- kind: ServiceAccount
  name: servicedefinition
roleRef:
  kind: Role
  name: servicedefinition
  apiGroup: rbac.authorization.k8s.io
