kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: servicedefinition
subjects:
- kind: ServiceAccount
  name: servicedefinition
  namespace: operator-ns
roleRef:
  kind: ClusterRole
  name: servicedefinition
  apiGroup: rbac.authorization.k8s.io
