apiVersion: servicedefinition.sz-ybbs.ac.at/v1alpha1
kind: Servicedefinition
metadata:
  name: "apachetest"
  namespace: "manual-services"
spec:
  webserver:
    name: "Apache"
    version: "1"
  owner: apachetest
  purpose: operatorTest
